version: 0.0

Resources:
  - Remove-Image-For-Deleted-Cavaleiro:
      Type: AWS::Lambda::Function
      Properties:
        Name: Remove-Image-For-Deleted-Cavaleiro
        Alias: prod
        CurrentVersion: $LATEST
        TargetVersion: 1
