version: 0.2

phases:
    install:
        runtime-versions:
            dotnet: 6.0
        commands: 
            - echo "Installing .NET 6 ..."
    build:
        commands:
            - dotnet restore
            - dotnet build
            - cd test/remove-image-for-deleted-cavaleiro.Tests
            - dotnet test
            - cd ../..
    post_build: 
        commands:
            - cd src/remove-image-for-deleted-cavaleiro
            - dotnet publish -r linux-x64
            - echo "The application build and publish was successful!"
artifacts:
    files:
        - 'src/remove-image-for-deleted-cavaleiro/bin/Debug/net6.0/linux-x64/publish/**/*'
    discard-paths: yes
            